version: '3'
services:
  auth:
    build:
      context: ../images/service
    image: dms2223-service
    container_name: dms2223auth
    volumes:
      - ../../components/dms2223common:/tmp/deps/src/common:ro
      - ../../components/dms2223auth:/tmp/src:ro
      - ./dms2223-auth:/root/.config:ro
    networks:
      dms2223:
        ipv4_address: 172.10.1.10

  backend:
    build:
      context: ../images/service
    image: dms2223-service
    container_name: dms2223backend
    volumes:
      - ../../components/dms2223common:/tmp/deps/src/common:ro
      - ../../components/dms2223backend:/tmp/src:ro
      - ./dms2223-backend:/root/.config:ro
    networks:
      dms2223:
        ipv4_address: 172.10.1.20

  frontend:
    build:
      context: ../images/service

    image: dms2223-service
    container_name: dms2223frontend
    volumes:
      - ../../components/dms2223common:/tmp/deps/src/common:ro
      - ../../components/dms2223frontend:/tmp/src:ro
      - ./dms2223-frontend:/root/.config:ro
    networks:
      dms2223:
        ipv4_address: 172.10.1.30
    ports:
      - "8080:8080"

networks:
  dms2223:
    ipam:
      driver: default
      config:
        - subnet: '172.10.1.0/24'